sudo: false
language: cpp
compiler:
  - gcc
os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - libopenblas-dev
    - liblapack-dev
    - libatlas-base-dev

before install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
  - update-alternatives --config libblas.so.3

script:
  - mkdir build
  - cd build
  - cmake -D CMAKE_CXX_COMPILER=g++-7 ..
  - make
  - ./hw6Tests/02_ANCTests/02_runHW6ANCTests
